#!/bin/bash
sudo apt update
sudo apt install python3-pip -y
sudo apt install python3-dev -y  
sudo apt install nginx -y
sudo apt install python3-django -y
sudo apt install gunicorn -y
sudo pip3 install virtualenv 
mkdir /home/ubuntu/projectdir
cd /home/ubuntu/projectdir || exit
virtualenv env
source /home/ubuntu/projectdir/env/bin/activate
sudo chown -R ubuntu:ubuntu /home/ubuntu/projectdir/
pip install django gunicorn
sudo /home/ubuntu/projectdir/manage.py makemigrations
sudo /home/ubuntu/projectdir/manage.py migrate
deactivate
sudo touch /etc/systemd/system/gunicorn.socket
sudo chmod 777 /etc/systemd/system/gunicorn.socket
echo "[Unit]
Description=gunicorn socket
[Socket]
ListenStream=/run/gunicorn.sock
[Install]
WantedBy=sockets.target
" > /etc/systemd/system/gunicorn.socket
sudo touch /etc/systemd/system/gunicorn.service
sudo chmod 777 /etc/systemd/system/gunicorn.service
echo " [Unit]
Description=gunicorn daemon
Requires=gunicorn.socket
After=network.target
[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/projectdir
ExecStart=/home/ubuntu/projectdir/env/bin/gunicorn \
          --access-logfile - \
          --workers 3 \
          --bind unix:/run/gunicorn.sock \
          textutils.wsgi:application
[Install]
WantedBy=multi-user.target
" > /etc/systemd/system/gunicorn.service
sudo systemctl start gunicorn.socket
sudo systemctl enable gunicorn.socket
sudo touch /etc/nginx/sites-available/textutils
sudo chmod 777 /etc/nginx/sites-available/textutils
echo " server {
    listen 80;
    server_name 3.111.171.69;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/ubuntu/projectdir;
    }
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
} " > /etc/nginx/sites-available/textutils
sudo ln -s /etc/nginx/sites-available/textutils /etc/nginx/sites-enabled/
sudo systemctl restart nginx
